# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-28 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('aid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('cid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('aid', models.PositiveIntegerField()),
                ('sid', models.CharField(max_length=18)),
                ('comment', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StuArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=18)),
                ('aid', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=8)),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
