# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-28 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imust', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
