# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imust', '0002_comment_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='aid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='aid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stuart',
            name='aid',
            field=models.IntegerField(),
        ),
    ]
