# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-30 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imust', '0003_auto_20181229_2323'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('nid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('time', models.DateTimeField()),
            ],
        ),
    ]
