# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-30 04:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imust', '0004_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='time',
            field=models.TextField(),
        ),
    ]
