# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imust', '0005_auto_20181230_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StuArt',
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
