# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-12-30 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imust', '0006_auto_20181230_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='name',
            new_name='author',
        ),
    ]
